### ISSUE TITLE
Ertekeles

### ISSUE THREAD

**Issue by hegyhati** [Teaching-projects/januari-beadando-RagiBali1#1]

**Comment by hegyhati** [comment]
@RagiBali1 minimal beadandonak rendben van, de ha a felsobb jegyek valamelyikere hajtasz, akkor pimpeld meg meg valamivel. Otletek: 
 - kiszervezes fuggvenybe, es parameterkent varja, hoy hany kockaval dobtunk es hanyszor
 - a szimpla kiiratas helyett irj mondjuk egy fajlba, ami mondjuk egy html, es legyen egy szep tablazat (html-t elmeletileg tavaly tanultatok)

**Comment by RagiBali1** [comment]
@hegyhati koszonom. Ez igy most hanyas lenne?

**Comment by RagiBali1** [comment]
@hegyhati Irtam egy kicsit mas fele beadandot, remelem ez lehet negyes :) !

**Comment by hegyhati** [comment]
Az eredeti egy kettes igen, ez csak egyes, mert teljesen ugyanaz, mint a keddi orai feladat.

**Comment by RagiBali1** [comment]
Nem tudná megadni a kettest legyen szives? :(

**Comment by hegyhati** [comment]
De, az eredetire minden tovabbi nelkul, de azert irtam otleteket, mert orultem volna, ha jobb jegyet szerzel vele.
